# Generated by Django 5.2.8 on 2025-11-16 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('season', models.CharField(max_length=100, null=True)),
                ('unit', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nid_number', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_area', models.FloatField(null=True)),
                ('expected_yield', models.FloatField(null=True)),
                ('harvest_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Growing', 'Growing'), ('Harvested', 'Harvested'), ('Completed', 'Completed')], default='Growing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmarApp.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmarApp.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='CropExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Seed', 'Seed'), ('Fertilizer', 'Fertilizer'), ('Labor', 'Labor'), ('Pesticide', 'Pesticide'), ('Irrigation', 'Irrigation'), ('Other', 'Other')], max_length=50, null=True)),
                ('amount', models.FloatField(null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmarApp.farmrecord')),
            ],
        ),
        migrations.CreateModel(
            name='FieldAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(default='Active', max_length=20, null=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='farmrecord',
            name='field_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmarApp.fieldagent'),
        ),
        migrations.CreateModel(
            name='FieldAgentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='farmarApp.farmer')),
                ('field_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmarApp.fieldagent')),
            ],
        ),
        migrations.AddField(
            model_name='farmer',
            name='field_agent_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_assignment', to='farmarApp.fieldagentassignment'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region_type', models.CharField(choices=[('Division', 'Division'), ('District', 'District'), ('Upazila', 'Upazila')], max_length=20)),
                ('parent_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmarApp.region')),
            ],
        ),
        migrations.AddField(
            model_name='fieldagent',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmarApp.region'),
        ),
        migrations.AddField(
            model_name='farmrecord',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmarApp.region'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmarApp.region'),
        ),
    ]
